"""NGINX reverse proxy config generation for service endpoints.

Generates NGINX server blocks from ServiceEndpoint records, enabling
subdomain-based routing to internal VM/container services.
"""

import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

NGINX_CONF_DIR = Path("/etc/nginx/conf.d/paws")
NGINX_TEMPLATE = """# Auto-generated by PAWS - do not edit manually
# Endpoint: {name} ({endpoint_id})
server {{
    listen 80;
    server_name {fqdn};

    location / {{
        proxy_pass {protocol}://{target_ip}:{port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        {websocket_headers}
        proxy_connect_timeout 60s;
        proxy_read_timeout 300s;
    }}
}}
"""

WEBSOCKET_HEADERS = """proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";"""


def generate_endpoint_config(endpoint: dict[str, Any]) -> str:
    """Generate an NGINX server block for a service endpoint."""
    ws_headers = WEBSOCKET_HEADERS if endpoint.get("enable_websocket") else ""

    return NGINX_TEMPLATE.format(
        name=endpoint["name"],
        endpoint_id=endpoint["id"],
        fqdn=endpoint["fqdn"],
        protocol=endpoint.get("protocol", "http"),
        target_ip=endpoint["target_ip"],
        port=endpoint["internal_port"],
        websocket_headers=ws_headers,
    )


def write_endpoint_config(endpoint_id: str, config: str) -> Path:
    """Write an endpoint config to the NGINX conf directory."""
    NGINX_CONF_DIR.mkdir(parents=True, exist_ok=True)
    conf_path = NGINX_CONF_DIR / f"paws-{endpoint_id}.conf"
    conf_path.write_text(config)
    logger.info("Wrote NGINX config: %s", conf_path)
    return conf_path


def remove_endpoint_config(endpoint_id: str) -> bool:
    """Remove an endpoint's NGINX config file."""
    conf_path = NGINX_CONF_DIR / f"paws-{endpoint_id}.conf"
    if conf_path.exists():
        conf_path.unlink()
        logger.info("Removed NGINX config: %s", conf_path)
        return True
    return False


def generate_all_configs(endpoints: list[dict[str, Any]]) -> list[str]:
    """Generate configs for all active endpoints."""
    configs = []
    for ep in endpoints:
        config = generate_endpoint_config(ep)
        configs.append(config)
    return configs
