"""add proxmox_volid to volumes

Revision ID: 18c279c5cb20
Revises: d0c2af214192
Create Date: 2026-03-06 14:24:02.428917
"""

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "18c279c5cb20"
down_revision: str | None = "d0c2af214192"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("volumes", sa.Column("proxmox_volid", sa.String(length=200), nullable=True))
    op.add_column("volumes", sa.Column("proxmox_owner_vmid", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("volumes", "proxmox_owner_vmid")
    op.drop_column("volumes", "proxmox_volid")
    # ### end Alembic commands ###
