"""add security_group_id to vpcs

Revision ID: 22025c1effec
Revises: 3cb77e634c99
Create Date: 2026-03-20 13:55:37.429502
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '22025c1effec'
down_revision: Union[str, None] = '3cb77e634c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpcs', sa.Column('security_group_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'vpcs', 'security_groups', ['security_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vpcs', type_='foreignkey')
    op.drop_column('vpcs', 'security_group_id')
    # ### end Alembic commands ###
