"""add max_backups and max_backup_size_gb to user_quotas

Revision ID: 4432dc981511
Revises: d5f2a8b91c03
Create Date: 2026-03-11 12:45:56.314324
"""

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "4432dc981511"
down_revision: str | None = "d5f2a8b91c03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("user_quotas", sa.Column("max_backups", sa.Integer(), nullable=False, server_default="20"))
    op.add_column("user_quotas", sa.Column("max_backup_size_gb", sa.Integer(), nullable=False, server_default="100"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_quotas", "max_backup_size_gb")
    op.drop_column("user_quotas", "max_backups")
    # ### end Alembic commands ###
