"""add tags to resources

Revision ID: 64eabb3d4910
Revises: 91ce5cd0520e
Create Date: 2026-03-03 10:28:59.375662
"""

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "64eabb3d4910"
down_revision: str | None = "91ce5cd0520e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("resources", sa.Column("tags", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resources", "tags")
    # ### end Alembic commands ###
