"""add template_catalog quota_requests system_settings

Revision ID: 91ce5cd0520e
Revises: 3658943f56bc
Create Date: 2026-03-03 10:25:22.768856
"""

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "91ce5cd0520e"
down_revision: str | None = "3658943f56bc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "template_catalog",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("proxmox_vmid", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("os_type", sa.String(length=50), nullable=True),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("min_cpu", sa.Integer(), nullable=False),
        sa.Column("min_ram_mb", sa.Integer(), nullable=False),
        sa.Column("min_disk_gb", sa.Integer(), nullable=False),
        sa.Column("icon_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("proxmox_vmid"),
    )
    op.create_index(op.f("ix_template_catalog_category"), "template_catalog", ["category"], unique=False)
    op.create_index(op.f("ix_template_catalog_is_active"), "template_catalog", ["is_active"], unique=False)
    op.create_table(
        "quota_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("request_type", sa.String(length=50), nullable=False),
        sa.Column("current_value", sa.Integer(), nullable=False),
        sa.Column("requested_value", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("admin_notes", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quota_requests_status"), "quota_requests", ["status"], unique=False)
    op.create_index(op.f("ix_quota_requests_user_id"), "quota_requests", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quota_requests_user_id"), table_name="quota_requests")
    op.drop_index(op.f("ix_quota_requests_status"), table_name="quota_requests")
    op.drop_table("quota_requests")
    op.drop_index(op.f("ix_template_catalog_is_active"), table_name="template_catalog")
    op.drop_index(op.f("ix_template_catalog_category"), table_name="template_catalog")
    op.drop_table("template_catalog")
    op.drop_table("system_settings")
    # ### end Alembic commands ###
