"""add SDN networking fields and models

Revision ID: ccad38e35da2
Revises: 4432dc981511
Create Date: 2026-03-12 12:29:18.081938
"""

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "ccad38e35da2"
down_revision: str | None = "4432dc981511"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vpc_peerings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("network_a_id", sa.UUID(), nullable=False),
        sa.Column("network_b_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["network_a_id"],
            ["vpcs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["network_b_id"],
            ["vpcs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ip_reservations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subnet_id", sa.UUID(), nullable=False),
        sa.Column("ip_address", sa.String(length=20), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("is_gateway", sa.Boolean(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["resources.id"],
        ),
        sa.ForeignKeyConstraint(["subnet_id"], ["subnets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subnet_id", "ip_address", name="uq_subnet_ip"),
    )
    op.create_index(op.f("ix_ip_reservations_owner_id"), "ip_reservations", ["owner_id"], unique=False)
    op.create_index(op.f("ix_ip_reservations_subnet_id"), "ip_reservations", ["subnet_id"], unique=False)
    op.add_column(
        "resources", sa.Column("network_mode", sa.String(length=20), server_default="private", nullable=False)
    )
    op.add_column("resources", sa.Column("bandwidth_limit_mbps", sa.Integer(), nullable=True))
    op.add_column("subnets", sa.Column("snat_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False))
    op.add_column("subnets", sa.Column("dhcp_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column("subnets", sa.Column("dhcp_start", sa.String(length=20), nullable=True))
    op.add_column("subnets", sa.Column("dhcp_end", sa.String(length=20), nullable=True))
    op.add_column("subnets", sa.Column("dns_server", sa.String(length=50), nullable=True))
    op.add_column("subnets", sa.Column("proxmox_subnet_id", sa.String(length=100), nullable=True))
    op.add_column("subnets", sa.Column("status", sa.String(length=20), server_default="active", nullable=False))
    op.add_column("user_quotas", sa.Column("max_networks", sa.Integer(), server_default="3", nullable=False))
    op.add_column("user_quotas", sa.Column("max_subnets_per_network", sa.Integer(), server_default="5", nullable=False))
    op.add_column("user_quotas", sa.Column("max_elastic_ips", sa.Integer(), server_default="5", nullable=False))
    op.add_column("user_tiers", sa.Column("bandwidth_limit_mbps", sa.Integer(), server_default="100", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_tiers", "bandwidth_limit_mbps")
    op.drop_column("user_quotas", "max_elastic_ips")
    op.drop_column("user_quotas", "max_subnets_per_network")
    op.drop_column("user_quotas", "max_networks")
    op.drop_column("subnets", "status")
    op.drop_column("subnets", "proxmox_subnet_id")
    op.drop_column("subnets", "dns_server")
    op.drop_column("subnets", "dhcp_end")
    op.drop_column("subnets", "dhcp_start")
    op.drop_column("subnets", "dhcp_enabled")
    op.drop_column("subnets", "snat_enabled")
    op.drop_column("resources", "bandwidth_limit_mbps")
    op.drop_column("resources", "network_mode")
    op.drop_index(op.f("ix_ip_reservations_subnet_id"), table_name="ip_reservations")
    op.drop_index(op.f("ix_ip_reservations_owner_id"), table_name="ip_reservations")
    op.drop_table("ip_reservations")
    op.drop_table("vpc_peerings")
    # ### end Alembic commands ###
