"""add_tiers_rules_groups_templates_ha

Revision ID: d077d62160b2
Revises: d02a57772806
Create Date: 2026-03-06 15:37:15.590806
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd077d62160b2'
down_revision: Union[str, None] = 'd02a57772806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ha_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pve_group_name', sa.String(length=100), nullable=False),
    sa.Column('nodes', sa.Text(), nullable=False),
    sa.Column('restricted', sa.Boolean(), nullable=False),
    sa.Column('nofailback', sa.Boolean(), nullable=False),
    sa.Column('max_relocate', sa.Integer(), nullable=False),
    sa.Column('max_restart', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pve_group_name')
    )
    op.create_table('system_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_rules_category'), 'system_rules', ['category'], unique=False)
    op.create_table('user_tiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capabilities', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_groups_owner_id'), 'user_groups', ['owner_id'], unique=False)
    op.create_table('user_group_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_member')
    )
    op.create_index(op.f('ix_user_group_members_group_id'), 'user_group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_user_group_members_user_id'), 'user_group_members', ['user_id'], unique=False)
    op.create_table('group_resource_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('shared_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'resource_id', name='uq_group_resource')
    )
    op.create_index(op.f('ix_group_resource_shares_group_id'), 'group_resource_shares', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_resource_shares_resource_id'), 'group_resource_shares', ['resource_id'], unique=False)
    op.create_table('template_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('os_type', sa.String(length=50), nullable=True),
    sa.Column('min_cpu', sa.Integer(), nullable=False),
    sa.Column('min_ram_mb', sa.Integer(), nullable=False),
    sa.Column('min_disk_gb', sa.Integer(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_requests_user_id'), 'template_requests', ['user_id'], unique=False)
    op.add_column('users', sa.Column('tier_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'user_tiers', ['tier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'tier_id')
    op.drop_index(op.f('ix_template_requests_user_id'), table_name='template_requests')
    op.drop_table('template_requests')
    op.drop_index(op.f('ix_group_resource_shares_resource_id'), table_name='group_resource_shares')
    op.drop_index(op.f('ix_group_resource_shares_group_id'), table_name='group_resource_shares')
    op.drop_table('group_resource_shares')
    op.drop_index(op.f('ix_user_group_members_user_id'), table_name='user_group_members')
    op.drop_index(op.f('ix_user_group_members_group_id'), table_name='user_group_members')
    op.drop_table('user_group_members')
    op.drop_index(op.f('ix_user_groups_owner_id'), table_name='user_groups')
    op.drop_table('user_groups')
    op.drop_table('user_tiers')
    op.drop_index(op.f('ix_system_rules_category'), table_name='system_rules')
    op.drop_table('system_rules')
    op.drop_table('ha_groups')
    # ### end Alembic commands ###
