"""polymorphic_group_sharing

Revision ID: ef2bd0f7b7ce
Revises: 0452bacc98f7
Create Date: 2026-03-06 16:08:04.985496
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ef2bd0f7b7ce'
down_revision: Union[str, None] = '0452bacc98f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add columns as nullable first
    op.add_column('group_resource_shares', sa.Column('entity_type', sa.String(length=30), nullable=True))
    op.add_column('group_resource_shares', sa.Column('entity_id', sa.UUID(), nullable=True))

    # Backfill from existing resource_id
    op.execute("UPDATE group_resource_shares SET entity_type = 'resource', entity_id = resource_id WHERE resource_id IS NOT NULL")

    # Now set NOT NULL
    op.alter_column('group_resource_shares', 'entity_type', nullable=False, server_default='resource')
    op.alter_column('group_resource_shares', 'entity_id', nullable=False)

    op.alter_column('group_resource_shares', 'resource_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('uq_group_resource'), 'group_resource_shares', type_='unique')
    op.create_index(op.f('ix_group_resource_shares_entity_id'), 'group_resource_shares', ['entity_id'], unique=False)
    op.create_unique_constraint('uq_group_entity', 'group_resource_shares', ['group_id', 'entity_type', 'entity_id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_group_entity', 'group_resource_shares', type_='unique')
    op.drop_index(op.f('ix_group_resource_shares_entity_id'), table_name='group_resource_shares')
    op.create_unique_constraint(op.f('uq_group_resource'), 'group_resource_shares', ['group_id', 'resource_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('group_resource_shares', 'resource_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('group_resource_shares', 'entity_id')
    op.drop_column('group_resource_shares', 'entity_type')
    # ### end Alembic commands ###
